name: kyz_jubek
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  animated_text_kit: ^4.2.2
  firebase_database: ^10.2.1
  firebase_storage: ^11.2.1
  google_sign_in: ^6.1.1
  shared_preferences: ^2.1.1
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  image_picker: ^0.8.6+4
  intl: ^0.17.0
  webview_flutter: ^3.0.4
  pie_chart: ^5.3.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
