// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_CYckBBgZAvy-JVjs3myCnP5OLO8tSY',
    appId: '1:757265826712:android:021d94398ad3da41be61ed',
    messagingSenderId: '757265826712',
    projectId: 'kyz-jibek',
    storageBucket: 'kyz-jibek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1QnbkD1sclKfpGmAExxXNmDy7KqOiiA',
    appId: '1:757265826712:ios:acbf0ee390d2e4ebbe61ed',
    messagingSenderId: '757265826712',
    projectId: 'kyz-jibek',
    storageBucket: 'kyz-jibek.appspot.com',
    iosClientId: '757265826712-9nmiftud0sra106jb9lt5u7uu928n884.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyzJubek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1QnbkD1sclKfpGmAExxXNmDy7KqOiiA',
    appId: '1:757265826712:ios:9c109d99f7981228be61ed',
    messagingSenderId: '757265826712',
    projectId: 'kyz-jibek',
    storageBucket: 'kyz-jibek.appspot.com',
    iosClientId: '757265826712-g5batii5tthosp39a04ibtv3h8ihi192.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyzJubek.RunnerTests',
  );
}
